import Foundation

/// Every legend entry, in the order the agencies print them.
///
/// The symbols are vector PDFs in `Assets.xcassets/LegendSE` and `LegendNO`,
/// generated by `tools/extract_legend_symbols.py` (clipped straight out of
/// Lantmäteriet's own legend artwork) and `tools/build_no_legend_symbols.py`
/// (drawn from Kartverket's `Skjermkartografi.otf` using the glyph codes,
/// colours, sizes and dash patterns their "Spesifikasjon for skjermkartografi"
/// publishes). Neither set is redrawn by hand, so a symbol here cannot drift
/// from the one on the map.
///
/// `nativeName` is deliberately not localized: it is the official Swedish or
/// Norwegian term, kept alongside the translation so a name read off a trail
/// sign or a paper map can still be looked up.
enum LegendCatalog {
    /// Assets that are wider than they are tall and want a wide chip.
    static let lineAssets: Set<String> = [
        "LegendSE/trail_summer_marked", "LegendSE/trail_summer_winter_marked",
        "LegendSE/trail_winter_marked", "LegendSE/trail_summer_only_marked",
        "LegendSE/trail_recommended_unmarked", "LegendSE/trail_poorly_marked",
        "LegendSE/trail_ski", "LegendSE/trail_snowmobile",
        "LegendSE/trail_snowmobile_mandatory", "LegendSE/trail_reindeer_husbandry",
        "LegendSE/trail_boat", "LegendSE/trail_boat_portage",
        "LegendSE/reindeer_fence",
        "LegendNO/trail_marked", "LegendNO/trail_unmarked", "LegendNO/tractor_road",
        "LegendNO/offroad_route", "LegendNO/floodlit_trail", "LegendNO/ski_lift",
        "LegendNO/reindeer_fence", "LegendNO/pier",
    ]

    static let sweden: [LegendSection] = [
        LegendSection(
            title: "Trails and routes",
            entries: [
                LegendEntry(
                    asset: "LegendSE/trail_summer_marked",
                    title: "Marked hiking trail",
                    nativeName: "Markerad vandringsled"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_summer_winter_marked",
                    title: "Marked summer and winter trail",
                    nativeName: "Markerad sommar- och vinterled"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_winter_marked",
                    title: "Marked winter trail",
                    nativeName: "Markerad vinterled"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_summer_only_marked",
                    title: "Marked summer trail",
                    nativeName: "Markerad sommarled"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_recommended_unmarked",
                    title: "Recommended route, unmarked",
                    nativeName: "Lämplig färdväg, omarkerad"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_poorly_marked",
                    title: "Path that is hard to follow",
                    nativeName: "Svårorienterad gångstig"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_ski",
                    title: "Ski track",
                    nativeName: "Skidspår"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_snowmobile",
                    title: "Snowmobile route",
                    nativeName: "Färdväg vid skoteråkning"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_snowmobile_mandatory",
                    title: "Mandatory snowmobile route",
                    nativeName: "Påbjuden färdväg vid skoteråkning"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_reindeer_husbandry",
                    title: "Reindeer husbandry route",
                    nativeName: "Rennäringsled"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_boat",
                    title: "Boat route, rowing route",
                    nativeName: "Trafikerad båtled, roddled"
                ),
                LegendEntry(
                    asset: "LegendSE/trail_boat_portage",
                    title: "Boat portage",
                    nativeName: "Båtdrag"
                ),
            ]
        ),
        LegendSection(
            title: "Cabins and shelter",
            entries: [
                LegendEntry(
                    asset: "LegendSE/mountain_lodge",
                    title: "Mountain lodge",
                    nativeName: "Fjällstation"
                ),
                LegendEntry(
                    asset: "LegendSE/tourist_hut",
                    title: "Tourist hut, overnight hut",
                    nativeName: "Turiststuga, övernattningsstuga"
                ),
                LegendEntry(
                    asset: "LegendSE/solitary_cabin",
                    title: "Solitary mountain cabin",
                    nativeName: "Enslig stuga i fjällen"
                ),
                LegendEntry(
                    asset: "LegendSE/rest_cabin",
                    title: "Rest cabin",
                    nativeName: "Raststuga"
                ),
                LegendEntry(
                    asset: "LegendSE/wind_shelter",
                    title: "Wind shelter",
                    nativeName: "Vindskydd"
                ),
                LegendEntry(
                    asset: "LegendSE/sami_cot",
                    title: "Sami hut",
                    nativeName: "Kåta"
                ),
                LegendEntry(
                    asset: "LegendSE/blast_shelter",
                    title: "Blast shelter",
                    nativeName: "Skyddsvärn"
                ),
            ]
        ),
        LegendSection(
            title: "Facilities and crossings",
            entries: [
                LegendEntry(
                    asset: "LegendSE/parking",
                    title: "Parking",
                    nativeName: "Parkering"
                ),
                LegendEntry(
                    asset: "LegendSE/helipad",
                    title: "Helicopter pad",
                    nativeName: "Helikopterplats"
                ),
                LegendEntry(
                    asset: "LegendSE/emergency_phone",
                    title: "Emergency telephone",
                    nativeName: "Hjälptelefon"
                ),
                LegendEntry(
                    asset: "LegendSE/bridge",
                    title: "Bridge",
                    nativeName: "Bro"
                ),
                LegendEntry(
                    asset: "LegendSE/ford",
                    title: "Ford",
                    nativeName: "Vad"
                ),
            ]
        ),
        LegendSection(
            title: "Fences and restrictions",
            entries: [
                LegendEntry(
                    asset: "LegendSE/reindeer_fence",
                    title: "Reindeer fence",
                    nativeName: "Renstängsel"
                ),
                LegendEntry(
                    asset: "LegendSE/reindeer_corral",
                    title: "Reindeer corral",
                    nativeName: "Rengärde"
                ),
                LegendEntry(
                    asset: "LegendSE/area_no_tent_or_fire",
                    title: "Camping and open fires prohibited",
                    nativeName: "Tält- och eldningsförbud"
                ),
            ]
        ),
    ]

    static let norway: [LegendSection] = [
        LegendSection(
            title: "Trails and routes",
            entries: [
                LegendEntry(
                    asset: "LegendNO/trail_marked",
                    title: "Marked trail",
                    nativeName: "Merket sti"
                ),
                LegendEntry(
                    asset: "LegendNO/trail_unmarked",
                    title: "Unmarked trail",
                    nativeName: "Umerket sti"
                ),
                LegendEntry(
                    asset: "LegendNO/tractor_road",
                    title: "Tractor road, foot and cycle path",
                    nativeName: "Traktorveg, gang- og sykkelveg"
                ),
                LegendEntry(
                    asset: "LegendNO/offroad_route",
                    title: "Off-road vehicle route, summer",
                    nativeName: "Barmarksløype"
                ),
                LegendEntry(
                    asset: "LegendNO/floodlit_trail",
                    title: "Floodlit trail",
                    nativeName: "Lysløype"
                ),
                LegendEntry(
                    asset: "LegendNO/ski_lift",
                    title: "Ski lift",
                    nativeName: "Skitrekk"
                ),
            ]
        ),
        LegendSection(
            title: "Cabins and shelter",
            entries: [
                LegendEntry(
                    asset: "LegendNO/cabin_staffed",
                    title: "Staffed tourist cabin",
                    nativeName: "Betjent turisthytte"
                ),
                LegendEntry(
                    asset: "LegendNO/cabin_self_service",
                    title: "Self-service tourist cabin",
                    nativeName: "Selvbetjent turisthytte"
                ),
                LegendEntry(
                    asset: "LegendNO/cabin_unstaffed",
                    title: "Unstaffed tourist cabin",
                    nativeName: "Ubetjent turisthytte"
                ),
                // Kartverket specifies the same symbol for both of these, so the
                // two rows looking identical is correct and must not be "fixed".
                LegendEntry(
                    asset: "LegendNO/rest_cabin",
                    title: "Rest cabin",
                    nativeName: "Rastebu"
                ),
                LegendEntry(
                    asset: "LegendNO/lean_to",
                    title: "Lean-to shelter",
                    nativeName: "Gapahuk"
                ),
            ]
        ),
        LegendSection(
            title: "Facilities and crossings",
            entries: [
                LegendEntry(
                    asset: "LegendNO/campsite",
                    title: "Campsite",
                    nativeName: "Campingplass"
                ),
                LegendEntry(
                    asset: "LegendNO/parking",
                    title: "Parking",
                    nativeName: "Parkering"
                ),
                LegendEntry(
                    asset: "LegendNO/helipad",
                    title: "Large helicopter landing site",
                    nativeName: "Stor helikopterlandingsplass"
                ),
                LegendEntry(
                    asset: "LegendNO/pier",
                    title: "Pier and jetty",
                    nativeName: "Kai og brygge"
                ),
            ]
        ),
        LegendSection(
            title: "Fences and restrictions",
            entries: [
                LegendEntry(
                    asset: "LegendNO/reindeer_fence",
                    title: "Reindeer fence",
                    nativeName: "Reingjerde"
                )
            ]
        ),
    ]
}
